### ISSUE TITLE
After SSS execution hangs, the SSS is no longer invoked

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#447] opened 2017-09-08 09:34 UTC
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 04, 2017 at 00:08 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/252_

----

**What is the current behavior?**
If you are writing a SSS, and due to a mistake in your code the SSS hangs indefinitely, it is never invoked again after that.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
Minimal reproduction example: Create a SSS with the function below:
```
module.exports = function (event) {
  console.log(event.data)
  return new Promise(function (resolve, reject) {})
  //return {data: event.data}
}
```
Do a test run. This will hang forever. Save the function.
Reopen the function and change back to normal:
```
module.exports = function (event) {
  console.log(event.data)
  //return new Promise(function (resolve, reject) {})
  return {data: event.data}
}
```
Test run will complete successfully.
Now, when you trigger the SSS, it is **not** invoked.
The only option is to create a new SSS, and copy paste query + code.

**What is the expected behavior?**
SSS should continue to invoke normally, after the code error is fixed.

**Comment by sorenbs** [comment] 2017-09-08 16:35
@kbrandwijk just to make sure - after you change the code back to normal and do a test run. Do you remember to save the function again?

**Comment by kbrandwijk** [comment] 2017-09-08 17:09
Yes, whatever I do after that, the function will never run again.

**Comment by marktani** [comment] 2017-10-07 11:58
I cannot reproduce this. I proceeded as you described. When I trigger the function, it is invoked as expected.

Therefore, I'll close this.

**Closed by marktani** 2017-10-07 11:58 UTC
Labels: area/functions, component/core, kind/bug

**Comment by kbrandwijk** [comment] 2017-10-07 12:03
I can't reproduce this either.
