### ISSUE TITLE
Order by multiple fields and nested fields

### ISSUE THREAD

**Issue by alapini** [graphcool/graphcool#747] opened 2017-10-08 15:20 UTC
An idea of `graphql` query that accepts multiple fields and nested fields ordering :  
```graphql
query {
  allPosts ( orderBy: {
    createdAt : DESC,
    author:{
        username : ASC
    },
    title: ASC
  }) {
    id
    createdAt
    title
    content
    author {
      username
    }
  }
}
```

**Comment by kbrandwijk** [comment] 2017-10-08 15:26
See https://github.com/graphcool/graphcool/issues/62 for multiple fields, and https://github.com/graphcool/graphcool/issues/95 for nested fields.

**Comment by marktani** [comment] 2017-10-11 09:24
Thanks for your suggestion! Closing as duplicate of the mentioned issues 🙂

**Closed by marktani** 2017-10-11 09:24 UTC
