### ISSUE TITLE
Expose functions directly through the endpoint

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#811] opened 2017-10-14 11:19 UTC
For **feature requests**, please fill in the next sections:

**What feature are you missing?**
I saw a FR a while ago about exposing functions directly as endpoints (can't find it anymore, please link it if found). This is useful for any project that now requires an external webtask, because of a callback URL, or the file-proxy for example.
As function exexution has now moved to AWS, and the project file has matured a lot, I think the steps to achieve this now are minimal.

**How could this feature look like in detail? Tradeoffs?**
I would propose adding another function type to the project definition, something like `endpoint` or something (needs a better term). Those functions would be available directly through `https://api.graph.cool/simple/v1/c......./functionName`. They probably also need a HTTP method (get/post).

**Comment by marktani** [comment] 2017-10-14 11:23
Closed as duplicate of #354.

**Closed by marktani** 2017-10-14 11:23 UTC
