### ISSUE TITLE
children_every and children_none filters also return parents without children

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#444] opened 2017-09-08 09:34 UTC
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Wednesday Aug 30, 2017 at 16:36 GMT_
_Originally opened as https://github.com/graphcool/api-bugs/issues/249_

----

**What is the current behavior?**
If you use `children_every` or `children_none`, the result set also includes parents without children.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
Schema:
```graphql
type Card implements Node {
  colors: [Color!]! @relation(name: "CardOnColor")
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}

type Color implements Node {
  card: Card @relation(name: "CardOnColor")
  color: String!
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```
Data:
```
One card without any colors, one card with one or more colors
```
Query:
```graphql
{
  allCards(filter: {colors_every: {color_in: ["black", "blue"]}}) {
    id
    colors {
      id
      color
    }
  }
}
```
Result:
```json
{
  "data": {
    "allCards": [
      {
        "id": "cj6z8d5yzlnh101661rbq0m7m",
        "colors": [
          {
            "id": "cj6z8cw1klmhn0150k8ofpneq",
            "color": "blue"
          },
          {
            "id": "cj6z8czwelngs01667xy0eulf",
            "color": "black"
          }
        ]
      },
      {
        "id": "cj6z8d9dhlnh901660t3j9d11",
        "colors": []
      }
    ]
  }
}
```
**What is the expected behavior?**
The node without colors should not be returned.

**Comment by sorenbs** [comment] 2017-09-08 16:41
@kbrandwijk This is intended behaviour and consistent with http://underscorejs.org/#every

The mental model is that

For **_every** if the relation is empty, then all children satisfy the condition
For **_none** if the relation is empty, then no children satisfy the condition

Do you think this is a bad mental model?

**Comment by marktani** [comment] 2017-09-08 16:56
I agree that the current behaviour is desired. It might be confusing, but you can adjust your query like this:

```
{
  allCards(filter: {
    colors_some: {
      id_not: null
    }
    colors_every: {
      color_in: ["black", "blue"]
    }
  }) {
    id
    colors {
      id
      color
    }
  }
}
```

to only get the first card and not the card without colors in your example.

**Comment by kbrandwijk** [comment] 2017-09-08 17:03
@marktani I read the last query, and it makes sense, but it's counter-intuitive.
Also, the _every behavior is counter-intuitive, but at least there's a way around it...

**Comment by marktani** [comment] 2017-09-08 17:10
I think it's at least as counter-intuitive to change it. Currently, it behaves the same as formal logic does. Here's a discussion about why a statement like "something holds true for all elements of the empty set" is always right: https://math.stackexchange.com/questions/202452/why-is-predicate-all-as-in-allset-true-if-the-set-is-empty.

**Comment by sorenbs** [comment] 2017-09-08 20:03
🤓

**Comment by marktani** [comment] 2017-09-11 09:17
I still think the filter system can be made more intuitive, but for lack of a better alternative, I'm closing this one. Please open a new issue if you have a suggestion.

**Closed by marktani** 2017-09-11 09:17 UTC
Labels: stage/discussing
