### ISSUE TITLE
new enum feature - migration values

### ISSUE THREAD

**Issue by stlbucket** [graphcool/graphcool#196] opened 2017-05-08 21:11 UTC
when changing enum values with the new enum feature and deleting an existing in-use value, there is no way to add a migration value.   there is still an error, but i am unable to update my enum values.

assuming this works if a migration value is assigned through the schema/field interface, but i already deleted that data.

in any event, there should be a place for migration value directly in the enum edit context

**Comment by stlbucket** [comment] 2017-05-08 21:42
also, if you delete the previous default value, then that value is not removed as the default.  if you then create a new instance of the type containing the enum, an error is thrown.

requestID: cj2gnh0660uqx01014rk3vfcj   may help you see this error

**Comment by marktani** [comment] 2017-09-19 16:36
Closing as duplicate of #305.

**Closed by marktani** 2017-09-19 16:36 UTC
Labels: kind/feature, stage/discussing
