### ISSUE TITLE
Schema is not syncing if I change the @relation name

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#764] opened 2017-10-10 17:03 UTC
_From @welf on October 10, 2017 16:39_

Hi! I've experimented with my test app and worked with GraphQL schema locally in Emacs. I've changed the `@relation` name, launched `graphcool status` and got:
```
Project ID: cj8kamumd06qv0177zzdxv53v
Remote Schema Version: 6

Everything up-to-date.
```

`graphcool push` doesn't sync schema as well. 

Is it a bug or a feature? ;)

_Copied from original issue: graphcool/graphql-cli#35_

**Comment by schickling** [comment] 2017-10-10 17:04
Thanks a lot for reporting this @welf. This is definitely a bug - we'll look into it!

**Comment by kbrandwijk** [comment] 2017-10-10 20:20
Duplicate of #700

**Closed** 2017-10-10 20:34 UTC
Labels: component/framework/deployment, kind/bug
