### ISSUE TITLE
FR: Add a 'currentTypeExists' query to the permissions endpoint

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#577] opened 2017-09-21 15:26 UTC
Now that reusability of permission queries has finally arrived with the new CLI beta, it would be great if you could reuse PQ's more easily by making them type-independent. I would like to have a `CurrentTypeExists` or `NodeTypeExists` or similar, that will take the current node type. That way, a 'only the owner' type PQ would be more easily reusable across many Types.

**Comment by marktani** [comment] 2017-09-21 15:31
I love it! Closing as duplicate of #189.

**Closed by marktani** 2017-09-21 15:31 UTC
Labels: area/permissions
