### ISSUE TITLE
Use Auth0 extend for functions not depending of SSS / request pipeline

### ISSUE THREAD

**Issue by THook** [graphcool/graphcool#573] opened 2017-09-18 23:51 UTC
**What feature are you missing?**
I have some custom code not depending of server-side subscriptions. Having a way to register functions using Auth0 extend without having to create an account anywhere else is a must.

Example use case with Twilio chat :
- users can join groups and each group has a dedicated Twilio chat room
- server-side subscriptions allow you to manage chat onCreate, onUpdate and onDelete
- the same way, you use SSS to add/delete a Gcool user to corresponding chat room
- the real problem comes when you have to request an access token for your user to enter the chat room : entering the room doesn't correspond to any event on Graphcool's backend

The solution right now is to create a custom function **somewhere else** like in Webtask or something. This is a big tradeoff in terms of code management.

Allowing your users to create functions and giving them a url to request on client-side would pretty much solve this (relatively common) issue.

**How could this feature look like in detail? Tradeoffs?**

- Click on Functions tab
- create a function outside of SSS / request pipeline
- give back a url created by Auth0 extend

This would even allow users to perform cron jobs in a much easier way before the features comes out!

What do you guys think about that? Extend probably allows you to do that pretty easily 👍

**Comment by marktani** [comment] 2017-09-19 09:34
Hey @THook, thanks *a lot* for your brilliant write up 🙂 I can't wait for Graphcool webhooks, they will cover so many workflows!

I'm closing this anyway as a duplicate of https://github.com/graphcool/graphcool/issues/354

**Closed by marktani** 2017-09-19 09:34 UTC
Labels: area/functions
