### ISSUE TITLE
Using "Reset model and Data" breaks File and User types

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#583] opened 2017-09-25 09:29 UTC
**What is the current behavior?**

If you reset your project models & data in the project settings of the Console, the project becomes inaccessible afterwards. The logs show a connection to the `User` and `File` types that are now missing, but are tried to be accessed.

The project becomes inaccessible and opening it in the Console leads to an internal server error.

**What is the expected behavior?**

Resetting project models & data doesn't break a project.

**Comment by do4gr** [comment] 2017-09-28 15:19
Can't reproduce this at the moment. Closing this.

**Closed by do4gr** 2017-09-28 15:19 UTC
Labels: component/core/system-api, kind/bug, milestone/0.5
