### ISSUE TITLE
Import feature

### ISSUE THREAD

**Issue by schickling** [graphcool/graphcool#615] opened 2017-09-28 12:27 UTC
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Jun 29, 2017 at 11:56 GMT_
_Originally opened as https://github.com/graphcool/cli/pull/117_

----

WIP - Do not merge.
https://github.com/kbrandwijk/graphcool-cli/issues/4

----

_**[kbrandwijk](https://github.com/kbrandwijk)** included the following code: https://github.com/graphcool/cli/pull/117/commits_

**Comment by schickling** [comment] 2017-09-28 12:27
<a href="https://github.com/cjoudrey"><img src="https://avatars1.githubusercontent.com/u/385270?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cjoudrey](https://github.com/cjoudrey)**
_Thursday Jun 29, 2017 at 18:02 GMT_

----

This is super interesting!

I might have missed this in the code, but what is the strategy for resuming an import that failed midway?

Should we require people to have an `oldid` (or `id`) that the import tool can use to `upsert` instead of inserting the same data twice?

**Comment by schickling** [comment] 2017-09-28 12:27
<a href="https://github.com/aurnik"><img src="https://avatars2.githubusercontent.com/u/3023219?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [aurnik](https://github.com/aurnik)**
_Tuesday Aug 29, 2017 at 01:58 GMT_

----

@kbrandwijk How is the progress on this? Is there anything that we can help with? Seems like a pretty important feature.

**Comment by schickling** [comment] 2017-09-28 12:27
<a href="https://github.com/mattfysh"><img src="https://avatars3.githubusercontent.com/u/470258?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattfysh](https://github.com/mattfysh)**
_Monday Sep 18, 2017 at 02:58 GMT_

----

Also happy to help out on this one, looking to push live in the next week or so and not sure I can do it without some kind of production-grade data backup/restoration

**Comment by schickling** [comment] 2017-09-28 12:27
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Sep 18, 2017 at 11:10 GMT_

----

@aurnik @mattfysh Further development of this feature will be coordinated by @timsuchanek.

**Comment by schickling** [comment] 2017-09-28 12:27
<a href="https://github.com/timsuchanek"><img src="https://avatars1.githubusercontent.com/u/1094804?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timsuchanek](https://github.com/timsuchanek)**
_Wednesday Sep 27, 2017 at 15:09 GMT_

----

Thanks @aurnik and @mattfysh and @kbrandwijk, we will wait with this until we enable custom ids in Graphcool. It is high on our priority list, so soon this should move forward

**Comment by marktani** [comment] 2017-09-29 15:41
closing as duplicate of #610.

**Closed by marktani** 2017-09-29 15:41 UTC
