### ISSUE TITLE
Support returning an Array from an SE

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphcool#356] opened 2017-08-31 17:51 UTC
As mentioned https://github.com/graphcool/feature-requests/issues/318#issuecomment-322230474 and https://www.graph.cool/forum/t/returning-an-array-from-a-se/763.

**Comment by marktani** [comment] 2017-09-20 09:23
closing as duplicate of #435

**Closed by marktani** 2017-09-20 09:23 UTC
Labels: area/functions, area/functions/resolvers, component/engine, component/engine/system-api, kind/feature, milestone/1.5, stage/queued

**Comment by kbrandwijk** [comment] 2017-09-20 11:05
Usually, duplicates work the other way around... E.g. newer one is usually the duplicate...
