### ISSUE TITLE
CLI updates permission even if it was not modified

### ISSUE THREAD

**Issue by l-catallo** [graphcool/graphcool#773] opened 2017-10-11 17:39 UTC
The CLI keeps replacing the permission queries on the targets even if no change was made to the sources.

Issuing a `graphcool diff` just after a deploy gives me this:
```
Your project xxxxxxxxxxxxxxx of env default has the following changes:

Model Permissions

  User
   - A permission for the operation `READ` is deleted.
   - A permission for the operation `UPDATE` is deleted.
   + A permission for the operation `READ` is created.
   + A permission for the operation `UPDATE` is created.
```

Version info: `graphcool/0.7.0-beta.5 (linux-x64) node-v8.6.0`

**Comment by marktani** [comment] 2017-10-11 19:32
Does that still happen when you do

```sh
graphcool deploy --force
graphcool diff
```
?

What's the current and the previous state of permissions in `graphcool.yml`?

**Comment by l-catallo** [comment] 2017-10-12 09:27
Using `--force` gives the same result.

This is the permissions configuration.
```
- operation: User.read
  authenticated: true
  query: ./permissions/authIsUserOwner.graphql
- operation: User.update
  authenticated: true
  query: ./permissions/authIsUserOwner.graphql
  fields:
  - createdAt
  - familyName
  - givenName
  - id
  - name
  - picture
  - updatedAt
```
There was no permissions set on the User type before.

**Comment by do4gr** [comment] 2017-10-12 09:34
Thanks for reporting this. I can reproduce it. Since I am already working in that area a fix should come out soon.

**Comment by marktani** [comment] 2017-10-20 12:51
This is now fixed.

**Closed by marktani** 2017-10-20 12:51 UTC
Labels: component/framework/deployment, kind/bug
