### ISSUE TITLE
Bug when setting up a project to run on different environment stages

### ISSUE THREAD

**Issue by ragzor** [graphcool/graphcool#1590] opened 2018-01-12 09:06 UTC
**Current behavior**
When selecting a new cluster for a different stage of an existing project using the interactive mode throws an error.

**Reproduction**

1. Create a new project using **graphql create**  chose boilerplate project as node-advanced
2. Add a new env file ".env.prod" change stage to "prod"
3. Run **graphcool deploy -e .env.prod**

CLI throws the following error:

![image](https://user-images.githubusercontent.com/1730252/34867254-72bb11d0-f7a5-11e7-8a72-a03a6c81de7d.png)

This is happening because the script adds a duplicate cluster key in the graphcool.yml file.

![image](https://user-images.githubusercontent.com/1730252/34867301-a0491638-f7a5-11e7-883f-57240781019a.png)

Deleting the duplicate key and adding the cluster value to the variables set in .env.prod then deploying again resolves the issue and generates a graphcool endpoint.

More Info: https://www.graph.cool/forum/t/1-0-different-environments-different-graphcool-yml-files/2105 

**Versions of graphcool and graphql-cli**

graphcool: graphcool/1.0.0-beta4.1.1
graphql-cli: 2.10.1

**Comment by timsuchanek** [comment] 2018-01-12 13:10
Thanks for reporting @ragzor.
I tried to reproduce your error, however, when using a `.env.prod` that looks like this, the dialog is not triggered:
```
NODE_ENV="prod"
GRAPHCOOL_STAGE="prod"
GRAPHCOOL_ENDPOINT="http://localhost:60000/project/prod"
GRAPHCOOL_CLUSTER="local"
GRAPHCOOL_SECRET="mysecret123"
APP_SECRET="jwtsecret123"
```
I could imagine that the `.env.prod` that you provided didn't include the `GRAPHCOOL_CLUSTER` env var. In that case, there should have been a warning:
```
~/c/brojek $ local-gc deploy -e .env.prod
 ▸    [WARNING] in /Users/tim/code/brojek/database/graphcool.yml: A valid
 ▸    environment variable to satisfy the declaration 'env:GRAPHCOOL_CLUSTER' could not be found.
```
Can you post the content of the `.env.prod` file when the error occured?

Thanks!

**Comment by ragzor** [comment] 2018-01-12 14:01
Hey @timsuchanek !

I was not entirely sure what to put in as cluster since I wanted it to be hosted online on a shared cluster hence I just kept the cluster variable empty like so:

`NODE_ENV="prod"
GRAPHCOOL_STAGE="prod"
GRAPHCOOL_ENDPOINT=""
GRAPHCOOL_CLUSTER=""
GRAPHCOOL_SECRET="mysecret123"
APP_SECRET="jwtsecret123"
`

Thanks!

**Comment by timsuchanek** [comment] 2018-01-12 15:00
Awesome, thanks for providing that information! That makes a lot of sense.
The CLI for now won't be that smart, that it's writing the result into the .env file, but it can write it directly into the graphcool.yml.
I added a better error for that case that explains the 2 options:
```
 ▸    Property cluster in graphcool.yml is provided, but provided value ${env:GRAPHCOOL_CLUSTER} could
 ▸    not be resolved. Make sure that the env var ${env:GRAPHCOOL_CLUSTER} is set correctly or remove
 ▸    the cluster property from the graphcool.yml and execute deploy again to get a new cluster.
```
I see the issue as resolved with this, if you have another issue related to this, please let me know.

The fix will be deployed in a beta release this week.

**Closed by timsuchanek** 2018-01-12 15:00 UTC
Labels: 1.0, component/cli, kind/bug
