### ISSUE TITLE
Error when trying to delete perm auth token in beta Console

### ISSUE THREAD

**Issue by mrwillis** [graphcool/graphcool#690] opened 2017-09-29 00:07 UTC
For **bug reports**, please fill in the next sections:

**What is the current behavior?**
An error occurs when clicking the trash can to delete a PAT

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**
I am currently following the e-mail password auth tutorial. I am using the beta with schema extensions. Currently trying to just delete a PAT. Here is the error. The PAT does not get deleted.

![image](https://user-images.githubusercontent.com/2652683/30995485-8b9bd204-a488-11e7-84d6-9bcd7baac7fe.png)

**If applicable, share the query, mutation or subscription for reproduction**

**What is the expected behavior?**
The PAT should delete after clicking confirm.

**Comment by mrwillis** [comment] 2017-09-29 00:42
Actually I currently cannot delete any PATs

**Comment by marktani** [comment] 2017-09-29 07:24
That's a duplicate of #524. Until this is fixed, please reach out to the support chat if you need urgent help with deleting a PAT.

**Closed by marktani** 2017-09-29 07:24 UTC
