### ISSUE TITLE
Allow returning of (nested) relational data on delete mutations

### ISSUE THREAD

**Issue by reinvanimschoot** [graphcool/graphcool#760] opened 2017-10-09 13:51 UTC
**What feature are you missing?**
It would be great if it was possible to return nested data of a relation in a delete mutation.

**An example:**
I delete a `like` or a `comment` that is linked to a `post` and in that same mutation, I would like to return the updated `commentCount` or `likeCount`. 

 Right now, it is not possible to return any information of the relations of a deleted entity.

<img width="470" alt="screen shot 2017-10-09 at 15 49 30" src="https://user-images.githubusercontent.com/19598519/31341368-9262a1ba-ad09-11e7-8f82-aa2db93221d4.png">

**How could this feature look like in detail? Tradeoffs?**

<img width="504" alt="screen shot 2017-10-09 at 15 47 13" src="https://user-images.githubusercontent.com/19598519/31341239-30e2fd5e-ad09-11e7-8058-8b5b18f8199e.png">

**Comment by marktani** [comment] 2017-10-11 09:31
thanks for this feature request! closing as duplicate of #108

**Closed by marktani** 2017-10-11 09:31 UTC
Labels: kind/feature
