### ISSUE TITLE
Import data using CLI

### ISSUE THREAD

**Issue by mkozhukharenko** [graphcool/graphcool#762] opened 2017-10-10 14:01 UTC
I'd be cool to have a possibility to just import data from another project (refill all data).

**What feature are you missing?**

Importing data from existing project.
I have three projects - dev, staging and prod. I don't want to manually copy all data form 'prod' to 'staging' in the admin panel.

**How could this feature look like in detail?**

```
graphcool import 'Project to copy from name'
```
or
```
graphcool import 'path to folder with json data which was exported form another project'
```

**Comment by marktani** [comment] 2017-10-11 09:33
closing as duplicate of #610

**Closed by marktani** 2017-10-11 09:33 UTC
