### ISSUE TITLE
Extending a Type with a custom resolver

### ISSUE THREAD

**Issue by FredyC** [graphcool/graphcool#348] opened 2017-08-21 07:02 UTC
Currently, it's possible to extend only Query/Mutation types. I am aware that by spec it shouldn't be possible to extend other types. However, we can add only fields/relations to the schema which is rather limited compared to being able to define the whole schema by ourselves. By the spec, you can have fields with variable input on the type.

```
extend type User {
  calcSomething(input: MyInput): Result
}
```

In the end, this also gives great power if you are querying the list of objects and you want to include calculated value as well. Without this and defining query at root level it means you have to run query separately for each received id and that's more than suboptimal.

```
query AllUsersWithCalc($input: MyInput) {
  allUsers {
    id
    calcSomething(input: $input)
  }
}
```

The key aspect is that a processing function would need to receive nodeId of its parent. Besides that the feature request #318 needs to be solved first to allow access to all types within schema extension SDL.

**Comment by marktani** [comment] 2017-09-18 11:42
That will be covered by custom field resolvers - duplicate of #56.

**Closed by marktani** 2017-09-18 11:42 UTC
Labels: area/functions, component/engine, kind/feature, stage/queued

**Comment by julius-e** [comment] 2019-02-10 23:10
I'm trying to implement a function that applies custom linear weights to a set of stats and return the total computed value for each row.

Typically one would send the weights to the server in the request, i.e.:
```graphql
# Linear weight to apply to each stat. Any field on Player can have a weight.
type Weights {
  stat1: Int,
  stat2: Int,
  ...
  statN: Int
}

# A 'Player' has stats.
type Player {
  stat1: Int,
  stat2: Int,
  ...
  statN: Int,

  #This field is the goal of the exercise:
  #Its value is given by: `SUM((stat1 * weight1),  ... (statN * weightN))`
  scrore: Int
}

type Query {
  getScores(weights: Weights, skip: Int, take: Int, orderBy: score_Desc): [Player!]!
}
```

This would be trivial in SQL:
```sql

SELECT stat1, stat1 * :weight1, stat2, stat2 * :weight2, ... statN, statN * :weightN
FROM PLAYERS
ORDER BY stat1 * :weight1 + stat2 * :weight2 + ... statN * :weightN DESC
LIMIT 10
```

I can eschew Prisma for this task and add a custom query + resolver in my application layer graphql server, but it would no longer conform to the API exposed by Prisma. Things like pagination and cursors would have to either be manually implemented or refactored into another paging mechanism. (i.e. the `skip` + `take` params above). 

Ideally a lambda that gets evaluated for each record at data retrieval time would be ideal. Obviously I do not know what is needed to make that happen, but I figured explaining my use case would be useful to the discussion since it seems pretty representative of the issue.

BTW I love Prisma. Keep up the great work!

**Comment by pantharshit00** [comment] 2019-02-11 06:56
This is possible with new Nexus library

https://github.com/prisma/nexus-prisma
